# The manifest for the "clera-main" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

# The name of the pipeline.
name: clera-main

# The version of the schema used in this template.
version: 1

# This section defines your source, changes to which trigger your pipeline.
source:
  # The name of the provider that is used to store the source artifacts.
  # (i.e. GitHub, Bitbucket, CodeCommit)
  provider: GitHub
  # Additional properties that further specify the location of the artifacts.
  properties:
    branch: main
    repository: https://github.com/clera-dev/clera
    # Uncomment and specify your connection name if you have one
    connection_name: copilot-clera-main

# This section defines the order of the environments your pipeline will deploy to.
stages:
  - # The name of the environment.
    name: production
    # Flag for manual approval action before deployment.
    # requires_approval: true  # Removed - PR approval is sufficient
    # Optional: use test commands to validate this stage of your build.
    # test_commands: [echo 'running tests', make test]

